#include "STeaMiIO.h"

codal::STeaMiIO::STeaMiIO()
    : p0(ID_PIN_P0, PinNumber::PC_4, PIN_CAPABILITY_ALL),
      p1(ID_PIN_P1, PinNumber::PA_5, PIN_CAPABILITY_ALL),
      p2(ID_PIN_P2, PinNumber::PC_5, PIN_CAPABILITY_ALL),
      p3(ID_PIN_P3, PinNumber::PA_2, PIN_CAPABILITY_ALL),
      p4(ID_PIN_P4, PinNumber::PA_4, PIN_CAPABILITY_ALL),
      p5(ID_PIN_P5, PinNumber::PA_7, PIN_CAPABILITY_DIGITAL),
      p6(ID_PIN_P6, PinNumber::PC_3, PIN_CAPABILITY_DIGITAL),
      p7(ID_PIN_P7, PinNumber::PA_9, PIN_CAPABILITY_DIGITAL),
      p8(ID_PIN_P8, PinNumber::PA_15, PIN_CAPABILITY_DIGITAL),
      p9(ID_PIN_P9, PinNumber::PC_2, PIN_CAPABILITY_DIGITAL),
      p10(ID_PIN_P10, PinNumber::PA_6, PIN_CAPABILITY_ALL),
      p11(ID_PIN_P11, PinNumber::PA_8, PIN_CAPABILITY_DIGITAL),
      p12(ID_PIN_P12, PinNumber::PC_6, PIN_CAPABILITY_DIGITAL),
      p13(ID_PIN_P13, PinNumber::PB_13, PIN_CAPABILITY_DIGITAL),
      p14(ID_PIN_P14, PinNumber::PB_14, PIN_CAPABILITY_DIGITAL),
      p15(ID_PIN_P15, PinNumber::PB_15, PIN_CAPABILITY_DIGITAL),
      p16(ID_PIN_P16, PinNumber::PE_4, PIN_CAPABILITY_DIGITAL),
      p19(ID_PIN_P19, PinNumber::PC_1, PIN_CAPABILITY_DIGITAL),
      p20(ID_PIN_P20, PinNumber::PC_0, PIN_CAPABILITY_DIGITAL),
      p24(ID_PIN_P24, PinNumber::NC, PIN_CAPABILITY_DIGITAL),
      p25(ID_PIN_P25, PinNumber::NC, PIN_CAPABILITY_DIGITAL),
      p28(ID_PIN_P28, PinNumber::NC, PIN_CAPABILITY_DIGITAL),
      p29(ID_PIN_P29, PinNumber::NC, PIN_CAPABILITY_DIGITAL),

      activate3V3StLink(ID_PIN_ACTIVATE_3V3_STLINK, PinNumber::PB_2, PIN_CAPABILITY_DIGITAL),

      csDisplay(ID_PIN_CS_DISPLAY, PinNumber::PD_0, PIN_CAPABILITY_DIGITAL),
      resetDisplay(ID_PIN_RST_DISPLAY, PinNumber::PA_12, PIN_CAPABILITY_DIGITAL),
      mosiDisplay(ID_PIN_SPI_INT_MOSI, PinNumber::PB_5, PIN_CAPABILITY_DIGITAL),
      misoDisplay(ID_PIN_SPI_INT_MISO, PinNumber::PB_4, PIN_CAPABILITY_DIGITAL),
      sckDisplay(ID_PIN_SPI_INT_SCK, PinNumber::PA_1, PIN_CAPABILITY_DIGITAL),

      extScl(ID_PIN_I2C_EXT_SCL, PinNumber::PC_0, PIN_CAPABILITY_DIGITAL),
      extsda(ID_PIN_I2C_EXT_SDA, PinNumber::PC_1, PIN_CAPABILITY_DIGITAL),

      intScl(ID_PIN_I2C_INT_SCL, PinNumber::PB_8, PIN_CAPABILITY_DIGITAL),
      intSda(ID_PIN_I2C_INT_SDA, PinNumber::PB_9, PIN_CAPABILITY_DIGITAL),

      irqAcc(ID_PIN_INT_ACC, PinNumber::PC_13, PIN_CAPABILITY_DIGITAL),
      irqDist(ID_PIN_INT_DIST, PinNumber::PB_12, PIN_CAPABILITY_DIGITAL),
      irqMag(ID_PIN_INT_MAG, PinNumber::PD_1, PIN_CAPABILITY_DIGITAL),
      irqExpander(ID_PIN_INT_EXPANDER, PinNumber::PB_0, PIN_CAPABILITY_DIGITAL),

      jacdacTx(ID_PIN_JACDAC_DATA_TX, PinNumber::PB_6, PIN_CAPABILITY_DIGITAL),
      jacdacRx(ID_PIN_JACDAC_DATA_RX, PinNumber::PB_7, PIN_CAPABILITY_DIGITAL),

      resetExpander(ID_PIN_RST_EXPANDER, PinNumber::PB_1, PIN_CAPABILITY_DIGITAL),

      serialRx(ID_PIN_SERIAL_RX, PinNumber::PB_10, PIN_CAPABILITY_DIGITAL),
      serialTx(ID_PIN_SERIAL_TX, PinNumber::PB_11, PIN_CAPABILITY_DIGITAL),

      mosi(ID_PIN_SPI_EXT_MOSI, PinNumber::PB_15, PIN_CAPABILITY_DIGITAL),
      miso(ID_PIN_SPI_EXT_MISO, PinNumber::PB_14, PIN_CAPABILITY_DIGITAL),
      sck(ID_PIN_SPI_EXT_SCK, PinNumber::PB_13, PIN_CAPABILITY_DIGITAL),
      cs(ID_PIN_SPI_EXT_CS, PinNumber::PE_4, PIN_CAPABILITY_DIGITAL),

      ledGreen(ID_PIN_LED_BLUE, PinNumber::PC_10, PIN_CAPABILITY_DIGITAL),
      ledBlue(ID_PIN_LED_GREEN, PinNumber::PC_11, PIN_CAPABILITY_DIGITAL),
      ledRed(ID_PIN_LED_RED, PinNumber::PC_12, PIN_CAPABILITY_DIGITAL),
      ledBLE(ID_PIN_LED_BLE, PinNumber::PH_3, PIN_CAPABILITY_DIGITAL),

      buttonA(ID_PIN_A_BUTTON, PinNumber::PA_7, PIN_CAPABILITY_DIGITAL),
      buttonB(ID_PIN_B_BUTTON, PinNumber::PA_8, PIN_CAPABILITY_DIGITAL),
      buttonMenu(ID_PIN_MENU_BUTTON, PinNumber::PA_0, PIN_CAPABILITY_DIGITAL),

      buttonUp(ID_PIN_UP_BUTTON, PinNumber::NC, PIN_CAPABILITY_DIGITAL),
      buttonDown(ID_PIN_DOWN_BUTTON, PinNumber::NC, PIN_CAPABILITY_DIGITAL),
      buttonLeft(ID_PIN_LEFT_BUTTON, PinNumber::NC, PIN_CAPABILITY_DIGITAL),
      buttonRight(ID_PIN_RIGHT_BUTTON, PinNumber::NC, PIN_CAPABILITY_DIGITAL),

      speaker(ID_PIN_SPEAKER, PinNumber::PA_11, PIN_CAPABILITY_DIGITAL),
      runmic(ID_PIN_MIC_CLK, PinNumber::PA_3, PIN_CAPABILITY_DIGITAL),
      microphone(ID_PIN_MIC_IN, PinNumber::PA_10, PIN_CAPABILITY_DIGITAL)
{
}
